### ISSUE TITLE
Pico tests failing gradient checks

### ISSUE THREAD

**Issue by Abai** [nyanp/tiny-cnn#93] opened 2016-02-10 12:17 UTC
Not sure if you noticed, but the current test.cpp fails like this:

`3 of 9 tests failed.
[ FAILED ] convolutional
gradient_check : /home/travis/build/nyanp/tiny-cnn/test/test.cpp(126): (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_ALL)) == true failed for: (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_ALL)) == false
gradient_check2 : /home/travis/build/nyanp/tiny-cnn/test/test.cpp(138): (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_ALL)) == true failed for: (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_ALL)) == false
gradient_check3 : /home/travis/build/nyanp/tiny-cnn/test/test.cpp(151): (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_ALL)) == true failed for: (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_ALL)) == false
gradient_check4 : /home/travis/build/nyanp/tiny-cnn/test/test.cpp(164): (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_ALL)) == true failed for: (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_ALL)) == false
gradient_check5 : /home/travis/build/nyanp/tiny-cnn/test/test.cpp(177): (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_ALL)) == true failed for: (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_ALL)) == false
[ FAILED ] multi_layer
gradient_check : /home/travis/build/nyanp/tiny-cnn/test/test.cpp(342): (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_RANDOM)) == true failed for: (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_RANDOM)) == false
gradient_check3 : /home/travis/build/nyanp/tiny-cnn/test/test.cpp(379): (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_RANDOM)) == true failed for: (nn.gradient_check(&a, &t, 1, 1e-4, GRAD_CHECK_RANDOM)) == false
[ FAILED ] multi_layer5
gradient_check : /home/travis/build/nyanp/tiny-cnn/test/test.cpp(417): (nn.gradient_check(&a, &t, 1, 5e-3, GRAD_CHECK_RANDOM)) == true failed for: (nn.gradient_check(&a, &t, 1, 5e-3, GRAD_CHECK_RANDOM)) == false`

The exact tests that fail seem to vary with every run. Is there some issue in these layers or is it just the test that needs fixing?

**Comment by nyanp** [comment] 2016-02-11 22:46
@Abai 
Thanks :) I've noticed, but I can't find the reason yet. In my windows environment, all tests are passed... Anyway, it's a bug of unit test or network.

**Comment by nyanp** [comment] 2016-02-14 15:07
It is caused by data race in gradient-check test code, and fixed in 635caff.

**Closed by nyanp** 2016-02-14 15:07 UTC
Labels: bug
